version: '3'
services:
  nginx:
    image: nginx:1.20.0-alpine
    volumes:
      - ./config/nginx.default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    depends_on:
      - php
    ports:
      - ${SERVER_PORT-80}:80
  php:
    image: php:8.0.5-fpm-alpine
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER-user}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD-secret}
      POSTGRES_DB: ${DATABASE_NAME-project}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT-5432}:5432
  composer:
    image: composer:2.0.13
    volumes:
      - ./app:/app
volumes:
  postgres-data: